import type { BambuFilamentMaterial, BambuFilamentPreset } from "./types";

const array = (value: string) => [value];

export const bambuCommonFilamentTemplate: BambuFilamentPreset = {
  type: "filament",
  from: "User",
  instantiation: "true",
  filament_settings_id: "",
  filament_diameter: array("1.75"),
  filament_shrink: array("100%"),
  filament_cost: array("0"),
  filament_adaptive_volumetric_speed: array("0"),
  filament_flush_temp: array("0"),
  filament_flush_temp_fast: array("0"),
  filament_flush_volumetric_speed: array("0"),
  volumetric_speed_coefficients: array("0 0 0 0 0 0"),
  filament_change_length: array("10"),
  filament_prime_volume: array("45"),
  filament_prime_volume_nc: array("60"),
  filament_minimal_purge_on_wipe_tower: array("15"),
  filament_cooling_before_tower: array("0"),
  filament_tower_interface_purge_volume: array("20"),
  filament_tower_interface_pre_extrusion_dist: array("10"),
  filament_tower_interface_pre_extrusion_length: array("0"),
  filament_tower_interface_print_temp: array("-1"),
  filament_tower_ironing_area: array("4"),
  filament_ramming_travel_time: array("0"),
  filament_ramming_travel_time_nc: array("0"),
  filament_ramming_volumetric_speed: array("-1"),
  filament_ramming_volumetric_speed_nc: array("-1"),
  close_fan_the_first_x_layers: array("3"),
  slow_down_for_layer_cooling: array("1"),
  no_slow_down_for_cooling_on_outwalls: array("0"),
  complete_print_exhaust_fan_speed: array("70"),
  during_print_exhaust_fan_speed: array("70"),
  filament_bridge_speed: array("25"),
  filament_enable_overhang_speed: array("1"),
  filament_overhang_1_4_speed: array("0"),
  filament_overhang_2_4_speed: array("50"),
  filament_overhang_3_4_speed: array("30"),
  filament_overhang_4_4_speed: array("10"),
  filament_overhang_totally_speed: array("10"),
  override_process_overhang_speed: array("0"),
  filament_retraction_length: array("nil"),
  filament_z_hop: array("nil"),
  filament_z_hop_types: array("nil"),
  filament_retraction_speed: array("nil"),
  filament_deretraction_speed: array("nil"),
  filament_retract_when_changing_layer: array("nil"),
  filament_wipe: array("nil"),
  filament_wipe_distance: array("nil"),
  filament_retract_before_wipe: array("nil"),
  filament_retraction_minimum_travel: array("nil"),
  filament_retract_restart_extra: array("nil"),
  filament_retract_length_nc: array("14"),
  filament_long_retractions_when_cut: array("nil"),
  filament_retraction_distances_when_cut: array("nil"),
  filament_long_retractions_when_ec: array("nil"),
  filament_retraction_distances_when_ec: array("nil"),
  long_retractions_when_ec: array("0"),
  retraction_distances_when_ec: array("0"),
  filament_pre_cooling_temperature: array("0"),
  filament_pre_cooling_temperature_nc: array("0"),
  filament_preheat_temperature_delta: array("10"),
  filament_printable: array("3"),
  filament_contact_safe: 1,
  filament_emission_safe: 1,
  filament_ingredients_safe: 1,
  filament_soluble: array("0"),
  filament_is_support: array("0"),
  filament_extruder_variant: array("Direct Drive Standard"),
  filament_extruder_compatibility: array("0"),
};

export const bambuFilamentMaterials: BambuFilamentMaterial[] = [
  {
    id: "generic-pla",
    name: "Generic PLA",
    type: "PLA",
    source: "Bambu Studio official open-source fdm_filament_pla / Generic PLA templates",
    sourcePath: "resources/profiles/BBL/filament/Generic PLA @base.json",
    templateInherits: "Generic PLA @base",
    inheritsPath: "resources/profiles/BBL/filament/Generic PLA @base.json",
    inheritsKind: "base_preset",
    importVerified: false,
    localPresetExists: true,
    defaultColor: "#f5f5f5",
    amsCompatibility: "Generally compatible; keep filament dry and check spool fit.",
    enclosureRecommendation: "Open or ventilated printing is usually preferred.",
    hardenedNozzleRecommendation: "Not required for ordinary PLA.",
    drying: "Dry if brittle or stringing; follow manufacturer TDS when available.",
    cooling: "High part cooling is commonly used for PLA.",
    advantages: ["Easy to print", "Low warping", "Good surface finish"],
    disadvantages: ["Lower heat resistance", "Can become brittle when wet"],
    notes: ["Use the manufacturer TDS when available.", "Run a small calibration print first."],
    template: {
      inherits: "Generic PLA @base",
      filament_type: array("PLA"),
      filament_vendor: array("Generic"),
      filament_density: array("1.24"),
      filament_flow_ratio: array("0.98"),
      filament_cost: array("20"),
      temperature_vitrification: array("45"),
      nozzle_temperature: array("220"),
      nozzle_temperature_initial_layer: array("220"),
      nozzle_temperature_range_low: array("190"),
      nozzle_temperature_range_high: array("240"),
      cool_plate_temp: array("35"),
      cool_plate_temp_initial_layer: array("35"),
      eng_plate_temp: array("0"),
      eng_plate_temp_initial_layer: array("0"),
      hot_plate_temp: array("55"),
      hot_plate_temp_initial_layer: array("55"),
      textured_plate_temp: array("55"),
      textured_plate_temp_initial_layer: array("55"),
      supertack_plate_temp: array("45"),
      supertack_plate_temp_initial_layer: array("45"),
      chamber_temperatures: array("0"),
      filament_max_volumetric_speed: array("12"),
      fan_min_speed: array("100"),
      fan_max_speed: array("100"),
      fan_cooling_layer_time: array("100"),
      slow_down_layer_time: array("8"),
      slow_down_min_speed: array("20"),
      overhang_fan_speed: array("100"),
      overhang_fan_threshold: array("50%"),
      additional_cooling_fan_speed: array("70"),
      close_additional_fan_first_x_layers: array("1"),
      close_fan_the_first_x_layers: array("1"),
      reduce_fan_stop_start_freq: array("1"),
      filament_dev_ams_drying_ams_limitations: ["1", "0"],
      filament_dev_ams_drying_heat_distortion_temperature: array("45"),
      filament_dev_ams_drying_temperature: ["45", "45", "45", "45"],
      filament_dev_ams_drying_time: ["12", "12", "12", "12"],
      filament_dev_chamber_drying_bed_temperature: array("70"),
      filament_dev_drying_cooling_temperature: array("45"),
      filament_dev_drying_softening_temperature: array("50"),
      filament_adhesiveness_category: array("100"),
      filament_metal_stickiness: array("None"),
      filament_printable: array("3"),
    },
  },
  {
    id: "generic-petg",
    name: "Generic PETG",
    type: "PETG",
    source: "Bambu Studio official open-source fdm_filament_pet / Generic PETG templates",
    sourcePath: "resources/profiles/BBL/filament/Generic PETG @base.json",
    templateInherits: "Generic PETG @base",
    inheritsPath: "resources/profiles/BBL/filament/Generic PETG @base.json",
    inheritsKind: "base_preset",
    importVerified: false,
    localPresetExists: true,
    defaultColor: "#d7dde2",
    amsCompatibility: "Usually compatible when dry; check spool dimensions and brittleness.",
    enclosureRecommendation: "Usually not required, but avoid drafts.",
    hardenedNozzleRecommendation: "Not required for ordinary non-filled PETG.",
    drying: "PETG is moisture-sensitive; dry according to manufacturer TDS when possible.",
    cooling: "Moderate cooling; excessive cooling can reduce layer adhesion.",
    advantages: ["Tougher than PLA", "Better heat resistance", "Good everyday functional material"],
    disadvantages: ["Can string if wet", "More prone to blobs and adhesion marks"],
    notes: ["Use glue or release agent when required by your plate.", "Screenshot values are not product data."],
    template: {
      inherits: "Generic PETG @base",
      filament_type: array("PETG"),
      filament_vendor: array("Generic"),
      filament_density: array("1.27"),
      filament_flow_ratio: array("0.95"),
      filament_cost: array("30"),
      temperature_vitrification: array("70"),
      nozzle_temperature: array("255"),
      nozzle_temperature_initial_layer: array("255"),
      nozzle_temperature_range_low: array("220"),
      nozzle_temperature_range_high: array("270"),
      cool_plate_temp: array("0"),
      cool_plate_temp_initial_layer: array("0"),
      eng_plate_temp: array("70"),
      eng_plate_temp_initial_layer: array("70"),
      hot_plate_temp: array("70"),
      hot_plate_temp_initial_layer: array("70"),
      textured_plate_temp: array("70"),
      textured_plate_temp_initial_layer: array("70"),
      supertack_plate_temp: array("70"),
      supertack_plate_temp_initial_layer: array("70"),
      chamber_temperatures: array("0"),
      filament_max_volumetric_speed: array("12"),
      fan_min_speed: array("40"),
      fan_max_speed: array("90"),
      fan_cooling_layer_time: array("30"),
      slow_down_layer_time: array("20"),
      slow_down_min_speed: array("20"),
      overhang_fan_speed: array("90"),
      overhang_fan_threshold: array("10%"),
      reduce_fan_stop_start_freq: array("1"),
      filament_dev_ams_drying_ams_limitations: ["1", "0"],
      filament_dev_ams_drying_heat_distortion_temperature: array("75"),
      filament_dev_ams_drying_temperature: ["65", "65", "55", "55"],
      filament_dev_ams_drying_time: ["12", "12", "12", "12"],
      filament_dev_chamber_drying_bed_temperature: array("80"),
      filament_dev_drying_cooling_temperature: array("55"),
      filament_dev_drying_softening_temperature: array("60"),
      filament_adhesiveness_category: array("300"),
      filament_metal_stickiness: array("High"),
      filament_printable: array("3"),
    },
  },
  {
    id: "generic-asa",
    name: "Generic ASA",
    type: "ASA",
    source: "Bambu Studio official open-source fdm_filament_asa template",
    sourcePath: "resources/profiles/BBL/filament/fdm_filament_asa.json",
    templateInherits: "fdm_filament_asa",
    inheritsPath: "resources/profiles/BBL/filament/fdm_filament_asa.json",
    inheritsKind: "inheritance_node",
    importVerified: false,
    localPresetExists: true,
    defaultColor: "#2f3136",
    amsCompatibility: "Compatible when dry; prefer sealed storage.",
    enclosureRecommendation: "Enclosure is recommended for dimensional stability and lower warping.",
    hardenedNozzleRecommendation: "Not required for ordinary non-filled ASA.",
    drying: "Dry according to manufacturer TDS; moisture can cause surface defects.",
    cooling: "Low to moderate cooling; prioritize layer adhesion and warping control.",
    advantages: ["UV and weather resistance", "Higher heat resistance than PLA/PETG", "Useful for outdoor parts"],
    disadvantages: ["Warping risk", "Fumes require ventilation", "Needs more controlled printing"],
    notes: ["Use an enclosure and ventilation.", "Check plate adhesion and avoid drafts."],
    template: {
      inherits: "fdm_filament_asa",
      filament_type: array("ASA"),
      filament_vendor: array("Generic"),
      filament_density: array("1.04"),
      filament_flow_ratio: array("1"),
      filament_cost: array("20"),
      temperature_vitrification: array("100"),
      nozzle_temperature: array("260"),
      nozzle_temperature_initial_layer: array("260"),
      nozzle_temperature_range_low: array("240"),
      nozzle_temperature_range_high: array("280"),
      cool_plate_temp: array("0"),
      cool_plate_temp_initial_layer: array("0"),
      eng_plate_temp: array("90"),
      eng_plate_temp_initial_layer: array("90"),
      hot_plate_temp: array("90"),
      hot_plate_temp_initial_layer: array("90"),
      textured_plate_temp: array("90"),
      textured_plate_temp_initial_layer: array("90"),
      supertack_plate_temp: array("0"),
      supertack_plate_temp_initial_layer: array("0"),
      chamber_temperatures: array("0"),
      filament_max_volumetric_speed: array("28.6"),
      fan_min_speed: array("10"),
      fan_max_speed: array("80"),
      fan_cooling_layer_time: array("35"),
      slow_down_layer_time: array("20"),
      slow_down_min_speed: array("20"),
      overhang_fan_speed: array("80"),
      overhang_fan_threshold: array("25%"),
      reduce_fan_stop_start_freq: array("1"),
      filament_dev_ams_drying_heat_distortion_temperature: array("100"),
      filament_dev_ams_drying_temperature: ["65", "80", "65", "80"],
      filament_dev_ams_drying_time: ["12", "8.0", "12", "8.0"],
      filament_dev_drying_cooling_temperature: array("85"),
      filament_dev_drying_softening_temperature: array("85"),
      filament_adhesiveness_category: array("200"),
      filament_metal_stickiness: array("None"),
      filament_printable: array("3"),
    },
  },
  {
    id: "bambu-pa-cf",
    name: "Bambu PA-CF",
    type: "PA-CF",
    source: "Bambu Studio official open-source Bambu PA-CF / Generic PA templates",
    sourcePath: "resources/profiles/BBL/filament/Bambu PA-CF @base.json",
    templateInherits: "Bambu PA-CF @base",
    inheritsPath: "resources/profiles/BBL/filament/Bambu PA-CF @base.json",
    inheritsKind: "base_preset",
    importVerified: false,
    localPresetExists: true,
    defaultColor: "#202020",
    amsCompatibility: "Use only if the spool and filament path are supported; keep dry.",
    enclosureRecommendation: "Enclosure and dry storage are recommended.",
    hardenedNozzleRecommendation: "Strongly recommended because carbon fiber is abrasive.",
    drying: "Dry before printing and store sealed; follow Bambu or manufacturer TDS.",
    cooling: "Low cooling is typical; prioritize layer adhesion.",
    advantages: ["High stiffness", "Good dimensional stability", "Engineering-grade functional parts"],
    disadvantages: ["Abrasive", "Moisture-sensitive", "More expensive and harder to print"],
    notes: ["Use a hardened nozzle and suitable extruder path.", "Run calibration before production parts."],
    template: {
      inherits: "Bambu PA-CF @base",
      filament_type: array("PA-CF"),
      filament_vendor: array("Bambu Lab"),
      filament_density: array("1.09"),
      filament_flow_ratio: array("0.96"),
      filament_cost: array("84.99"),
      temperature_vitrification: array("170"),
      nozzle_temperature: array("290"),
      nozzle_temperature_initial_layer: array("290"),
      nozzle_temperature_range_low: array("260"),
      nozzle_temperature_range_high: array("300"),
      cool_plate_temp: array("0"),
      cool_plate_temp_initial_layer: array("0"),
      eng_plate_temp: array("100"),
      eng_plate_temp_initial_layer: array("100"),
      hot_plate_temp: array("100"),
      hot_plate_temp_initial_layer: array("100"),
      textured_plate_temp: array("100"),
      textured_plate_temp_initial_layer: array("100"),
      supertack_plate_temp: array("0"),
      supertack_plate_temp_initial_layer: array("0"),
      chamber_temperatures: array("60"),
      filament_max_volumetric_speed: array("8"),
      fan_min_speed: array("10"),
      fan_max_speed: array("30"),
      fan_cooling_layer_time: array("5"),
      full_fan_speed_layer: array("2"),
      additional_fan_full_speed_layer: array("2"),
      slow_down_layer_time: array("65"),
      slow_down_min_speed: array("20"),
      overhang_fan_speed: array("40"),
      overhang_fan_threshold: array("0%"),
      filament_dev_ams_drying_heat_distortion_temperature: array("90"),
      filament_dev_ams_drying_temperature: ["65", "80", "65", "80"],
      filament_dev_ams_drying_time: ["12", "12", "12", "12"],
      filament_dev_chamber_drying_time: array("18"),
      filament_dev_drying_cooling_temperature: array("65"),
      filament_dev_drying_softening_temperature: array("85"),
      filament_adhesiveness_category: array("400"),
      filament_metal_stickiness: array("High"),
      filament_printable: array("3"),
    },
  },
];
