export type ManualParameterTemplateItem = {
  key: string;
  category: string;
  labelZh: string;
  labelEn: string;
  unit?: string;
};

function p(
  category: string,
  key: string,
  labelZh: string,
  labelEn: string,
  unit?: string,
): ManualParameterTemplateItem {
  return { category, key, labelZh, labelEn, unit };
}

export const manualParameterTemplateVersion = "manual-v1";

export const manualParameterTemplate: ManualParameterTemplateItem[] = [
  p("基础信息", "material_type", "材料类型", "Material Type"),
  p("基础信息", "material_subtype", "材料子类型", "Material Subtype"),
  p("基础信息", "product_line", "产品线", "Product Line"),
  p("基础信息", "variant", "变体", "Variant"),
  p("基础信息", "diameter", "线径", "Diameter", "mm"),
  p("基础信息", "net_weight", "净重", "Net Weight", "g"),
  p("基础信息", "gross_weight", "毛重", "Gross Weight", "g"),
  p("基础信息", "spool_weight", "盘重", "Spool Weight", "g"),
  p("基础信息", "filament_length", "耗材长度", "Filament Length", "m"),
  p("基础信息", "color_or_finish", "颜色/表面效果", "Color or Finish"),
  p("基础信息", "official_color_code", "官方色号", "Official Color Code"),
  p("基础信息", "printing_process", "适用工艺", "Printing Process"),
  p("基础信息", "official_product_url", "官方商品链接", "Official Product URL"),
  p("基础信息", "official_datasheet_url", "官方资料链接", "Official Datasheet URL"),
  p("耗材特性", "surface_finish", "表面效果", "Surface Finish"),
  p("耗材特性", "gloss_level", "光泽度", "Gloss Level"),
  p("耗材特性", "transparency", "透明度", "Transparency"),
  p("耗材特性", "flexibility", "柔韧性", "Flexibility"),
  p("耗材特性", "toughness", "韧性", "Toughness"),
  p("耗材特性", "brittleness_risk", "脆性风险", "Brittleness Risk"),
  p("耗材特性", "layer_adhesion", "层间结合", "Layer Adhesion"),
  p("耗材特性", "bridging_performance", "桥接表现", "Bridging Performance"),
  p("耗材特性", "overhang_performance", "悬垂表现", "Overhang Performance"),
  p("耗材特性", "stringing_tendency", "拉丝倾向", "Stringing Tendency"),
  p("耗材特性", "warping_tendency", "翘曲倾向", "Warping Tendency"),
  p("耗材特性", "shrinkage", "收缩率", "Shrinkage"),
  p("耗材特性", "odor", "气味", "Odor"),
  p("耗材特性", "moisture_sensitivity", "吸湿性", "Moisture Sensitivity"),
  p("耗材特性", "wear_resistance", "耐磨性", "Wear Resistance"),
  p("耗材特性", "weather_resistance", "耐候性", "Weather Resistance"),
  p("耗材特性", "uv_resistance", "耐紫外线", "UV Resistance"),
  p("耗材特性", "chemical_resistance", "耐化学性", "Chemical Resistance"),
  p("耗材特性", "impact_resistance", "耐冲击性", "Impact Resistance"),
  p("耗材特性", "food_contact_claim", "食品接触声明", "Food Contact Claim"),
  p("耗材特性", "eco_claim", "环保/可降解声明", "Eco or Biodegradable Claim"),
  p("打印温度", "nozzle_temperature", "喷嘴温度", "Nozzle Temperature", "C"),
  p("打印温度", "first_layer_nozzle_temperature", "首层喷嘴温度", "First Layer Nozzle Temperature", "C"),
  p("打印温度", "bed_temperature", "热床温度", "Bed Temperature", "C"),
  p("打印温度", "first_layer_bed_temperature", "首层热床温度", "First Layer Bed Temperature", "C"),
  p("打印温度", "chamber_temperature", "腔体温度", "Chamber Temperature", "C"),
  p("打印温度", "max_hotend_temperature", "热端最高建议温度", "Max Recommended Hotend Temperature", "C"),
  p("打印温度", "max_bed_temperature", "热床最高建议温度", "Max Recommended Bed Temperature", "C"),
  p("打印速度与流量", "recommended_print_speed", "建议打印速度", "Recommended Print Speed", "mm/s"),
  p("打印速度与流量", "first_layer_speed", "首层速度", "First Layer Speed", "mm/s"),
  p("打印速度与流量", "outer_wall_speed", "外墙速度", "Outer Wall Speed", "mm/s"),
  p("打印速度与流量", "inner_wall_speed", "内墙速度", "Inner Wall Speed", "mm/s"),
  p("打印速度与流量", "infill_speed", "填充速度", "Infill Speed", "mm/s"),
  p("打印速度与流量", "support_speed", "支撑速度", "Support Speed", "mm/s"),
  p("打印速度与流量", "max_volumetric_speed", "最大体积流速", "Max Volumetric Speed", "mm3/s"),
  p("打印速度与流量", "flow_ratio", "流量倍率", "Flow Ratio"),
  p("打印速度与流量", "pressure_advance", "压力提前", "Pressure Advance"),
  p("打印速度与流量", "line_width", "线宽建议", "Line Width Recommendation"),
  p("冷却与风扇", "fan_speed", "风扇速度", "Fan Speed", "%"),
  p("冷却与风扇", "first_layer_fan", "首层风扇", "First Layer Fan", "%"),
  p("冷却与风扇", "max_fan", "最大风扇", "Max Fan", "%"),
  p("冷却与风扇", "min_fan", "最小风扇", "Min Fan", "%"),
  p("冷却与风扇", "bridge_fan", "桥接风扇", "Bridge Fan", "%"),
  p("冷却与风扇", "fan_off_recommended", "是否建议关闭风扇", "Fan Off Recommended"),
  p("回抽与运动", "retraction_distance", "回抽距离", "Retraction Distance", "mm"),
  p("回抽与运动", "retraction_speed", "回抽速度", "Retraction Speed", "mm/s"),
  p("回抽与运动", "z_hop", "Z Hop", "Z Hop"),
  p("回抽与运动", "wipe", "擦嘴", "Wipe"),
  p("回抽与运动", "extra_restart_distance", "回抽额外重启量", "Extra Restart Distance"),
  p("回抽与运动", "acceleration", "加速度建议", "Acceleration Recommendation"),
  p("回抽与运动", "jerk", "Jerk 建议", "Jerk Recommendation"),
  p("热性能", "glass_transition_temperature", "玻璃化转变温度", "Glass Transition Temperature", "C"),
  p("热性能", "heat_deflection_temperature", "热变形温度", "Heat Deflection Temperature", "C"),
  p("热性能", "melting_point", "熔点", "Melting Point", "C"),
  p("热性能", "vicat_softening_temperature", "维卡软化温度", "Vicat Softening Temperature", "C"),
  p("热性能", "continuous_use_temperature", "连续使用温度", "Continuous Use Temperature", "C"),
  p("热性能", "short_term_heat_resistance", "短时耐温", "Short Term Heat Resistance", "C"),
  p("热性能", "annealable", "是否可退火", "Annealable"),
  p("热性能", "annealing_temperature", "退火温度", "Annealing Temperature", "C"),
  p("热性能", "annealing_time", "退火时间", "Annealing Time"),
  p("热性能", "annealing_shrinkage_risk", "退火收缩风险", "Annealing Shrinkage Risk"),
  p("机械性能", "tensile_strength", "拉伸强度", "Tensile Strength", "MPa"),
  p("机械性能", "flexural_strength", "弯曲强度", "Flexural Strength", "MPa"),
  p("机械性能", "flexural_modulus", "弯曲模量", "Flexural Modulus", "MPa"),
  p("机械性能", "impact_strength", "冲击强度", "Impact Strength"),
  p("机械性能", "elongation_at_break", "断裂伸长率", "Elongation at Break", "%"),
  p("机械性能", "hardness", "硬度", "Hardness"),
  p("机械性能", "density", "密度", "Density", "g/cm3"),
  p("机械性能", "rigidity", "刚性", "Rigidity"),
  p("机械性能", "toughness_level", "韧性等级", "Toughness Level"),
  p("机械性能", "fatigue_resistance", "耐疲劳性", "Fatigue Resistance"),
  p("干燥与保存", "drying_required", "是否需要干燥", "Drying Required"),
  p("干燥与保存", "drying_temperature", "干燥温度", "Drying Temperature", "C"),
  p("干燥与保存", "drying_time", "干燥时间", "Drying Time"),
  p("干燥与保存", "storage_humidity", "保存湿度", "Storage Humidity"),
  p("干燥与保存", "storage_method", "保存方式", "Storage Method"),
  p("干燥与保存", "recommended_use_after_opening", "开封后建议使用时间", "Recommended Use After Opening"),
  p("干燥与保存", "airtight_storage_required", "是否需要密封保存", "Airtight Storage Required"),
  p("干燥与保存", "dry_box_printing_required", "是否需要干燥盒打印", "Dry Box Printing Required"),
  p("打印机兼容性", "compatible_printers", "适用打印机", "Compatible Printers"),
  p("打印机兼容性", "compatible_nozzle", "适用喷嘴", "Compatible Nozzle"),
  p("打印机兼容性", "recommended_nozzle_material", "推荐喷嘴材质", "Recommended Nozzle Material"),
  p("打印机兼容性", "minimum_nozzle_diameter", "最小喷嘴直径", "Minimum Nozzle Diameter", "mm"),
  p("打印机兼容性", "ams_compatible", "是否适合 AMS", "AMS Compatible"),
  p("打印机兼容性", "multicolor_compatible", "是否适合多色打印", "Multicolor Compatible"),
  p("打印机兼容性", "enclosure_required", "是否需要封箱", "Enclosure Required"),
  p("打印机兼容性", "high_temperature_hotend_required", "是否需要高温热端", "High Temperature Hotend Required"),
  p("打印机兼容性", "abrasive", "是否磨喷嘴", "Abrasive"),
  p("打印机兼容性", "clogging_risk", "是否容易堵头", "Clogging Risk"),
  p("支撑与后处理", "support_compatibility", "支撑兼容性", "Support Compatibility"),
  p("支撑与后处理", "recommended_support_material", "推荐支撑材料", "Recommended Support Material"),
  p("支撑与后处理", "easy_support_removal", "是否易拆支撑", "Easy Support Removal"),
  p("支撑与后处理", "sandable", "是否可打磨", "Sandable"),
  p("支撑与后处理", "paintable", "是否可喷漆", "Paintable"),
  p("支撑与后处理", "glueable", "是否可粘接", "Glueable"),
  p("支撑与后处理", "polishable", "是否可抛光", "Polishable"),
  p("支撑与后处理", "surface_treatment_compatible", "是否可电镀/表面处理", "Surface Treatment Compatible"),
  p("安全与注意事项", "printing_odor_level", "打印气味等级", "Printing Odor Level"),
  p("安全与注意事项", "ventilation_recommended", "是否建议通风", "Ventilation Recommended"),
  p("安全与注意事项", "irritation_risk", "是否有刺激性", "Irritation Risk"),
  p("安全与注意事项", "child_product_claim", "儿童用品适用声明", "Child Product Claim"),
  p("安全与注意事项", "food_contact_suitability", "食品接触适用声明", "Food Contact Suitability"),
  p("安全与注意事项", "electrical_insulation", "电气绝缘性", "Electrical Insulation"),
  p("安全与注意事项", "flame_retardancy", "阻燃等级", "Flame Retardancy"),
  p("安全与注意事项", "warnings", "注意事项", "Warnings"),
  p("官方与人工备注", "official_recommended_settings", "官方推荐设置", "Official Recommended Settings"),
  p("官方与人工备注", "official_notes", "官方特殊说明", "Official Notes"),
  p("官方与人工备注", "manual_test_notes", "人工测试备注", "Manual Test Notes"),
  p("官方与人工备注", "recommended_use_cases", "适合用途", "Recommended Use Cases"),
  p("官方与人工备注", "not_recommended_use_cases", "不适合用途", "Not Recommended Use Cases"),
  p("官方与人工备注", "data_source", "数据来源", "Data Source"),
  p("官方与人工备注", "confidence_level", "可信度", "Confidence Level"),
];
